run:
  timeout: 10m
  modules-download-mode: vendor
  build-tags:
    - netgo
    - require_docker

output:
  format: line-number

linters:
  enable:
    - goimports
    - golint
    - misspell
    - gofmt

linters-settings:
  errcheck:
    exclude: .errcheck-exclude
  goimports:
    local-prefixes: "github.com/grafana/cortextool"
